import { getRefName, getSchemaName, getTsType } from "./utils.mjs";
import { AUTOGENERATED_COMMENT } from "./strings.mjs";
import { getJsdoc } from "../utilities/jsdoc.mjs";
import { isAscending } from "../utils.mjs";
/** Generates TypeScript type definitions from an array of type ASTs */
function generateTypes(types, config) {
    let code = AUTOGENERATED_COMMENT;
    const sortedTypes = types.sort(({ name }, { name: otherName }) => isAscending(name, otherName));
    const schemasMap = buildSchemasMap(sortedTypes);
    for (const typeAST of sortedTypes) {
        try {
            code += generateSingleType(typeAST, config, schemasMap);
        }
        catch (error) {
            console.error(`Failed to generate type for "${typeAST.name}":`, error);
        }
    }
    return code;
}
/** Build a map of all schemas for discriminator resolution */
function buildSchemasMap(types) {
    const schemasMap = new Map();
    for (const { name, schema } of types) {
        if (schema) {
            schemasMap.set(getSchemaName(name), schema);
        }
    }
    return schemasMap;
}
/** Generate a single type definition with JSDoc */
function generateSingleType(typeAST, config, schemasMap) {
    const { name: typeName, schema, description } = typeAST;
    const name = getSchemaName(typeName);
    const jsdoc = getJsdoc(Object.assign(Object.assign({}, schema), { description: description || (schema === null || schema === void 0 ? void 0 : schema.description), deprecated: (schema === null || schema === void 0 ? void 0 : schema.deprecated)
            ? (schema === null || schema === void 0 ? void 0 : schema["x-deprecatedMessage"]) || String(schema === null || schema === void 0 ? void 0 : schema.deprecated)
            : undefined }));
    const typeDefinition = getTypeDefinition(name, schema, config, schemasMap);
    return `
    ${jsdoc}
    ${typeDefinition}
    `;
}
/** Generate a TypeScript type definition for a given schema */
function getTypeDefinition(name, schema = {}, config, schemasMap) {
    // Handle enums
    if (schema.enum) {
        return generateEnumDefinition(name, schema.enum, schema["x-enumNames"], config);
    }
    // Handle allOf/oneOf compositions
    if (schema.allOf || schema.oneOf) {
        return `export type ${name} = ${getTsType(schema, config, schemasMap, name)};`;
    }
    // Handle arrays
    if (schema.type === "array" && schema.items) {
        return `export type ${name} = (${getTsType(schema.items, config, schemasMap)})[];`;
    }
    // Handle references
    if (schema.$ref) {
        return `export type ${name} = ${getRefName(schema.$ref)};`;
    }
    // Handle objects
    if (schema.type === "object") {
        return generateObjectType(name, schema, config, schemasMap);
    }
    // Handle primitive types
    if (schema.type === "string") {
        return `export type ${name} = string;`;
    }
    // Fallback
    return `export type ${name} = any;`;
}
/** Generate object type or interface */
function generateObjectType(name, schema, config, schemasMap) {
    const typeObject = getTsType(schema, config, schemasMap);
    const hasProperties = schema.additionalProperties || schema.properties;
    const hasOneOf = schema.oneOf;
    if (hasProperties && !hasOneOf) {
        return `export interface ${name} ${typeObject}`;
    }
    return `export type ${name} = ${typeObject};`;
}
/** Generate enum definition as type union or enum based on config */
function generateEnumDefinition(name, enumValues, enumNames, config) {
    if (config.generateEnumAsType) {
        return generateEnumAsTypeUnion(name, enumValues);
    }
    return generateEnumAsEnum(name, enumValues, enumNames);
}
/** Generate enum as a type union */
function generateEnumAsTypeUnion(name, enumValues) {
    const unionString = enumValues.length
        ? enumValues.map((value) => JSON.stringify(value)).join(" | ")
        : "unknown";
    return `export type ${name} = ${unionString};`;
}
/** Generate enum as a TypeScript enum */
function generateEnumAsEnum(name, enumValues, enumNames) {
    const entries = enumValues.map((value, index) => {
        var _a;
        const key = (_a = enumNames === null || enumNames === void 0 ? void 0 : enumNames[index]) !== null && _a !== void 0 ? _a : JSON.stringify(value);
        return `"${key.replace(/"/g, "")}"=${JSON.stringify(value)}`;
    });
    return `export enum ${name} {${entries.join(",")}}`;
}
export { generateTypes };
//# sourceMappingURL=generateTypes.mjs.map